---
title: "Jonah's Blog"
date: 2020-06-07
---
title: Jonah's Profile
author: Jonah Huang
email: jonahh0987@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This is my amazing profile of myself! Enjoy your stay!

twitter_username: jhviper
github_username:  jonahh0987

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
